// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAneAIVn0M_zfFQhkVrPw-RoSm-x0FIN8w',
    appId: '1:12011738615:web:985559380d4c334a874af2',
    messagingSenderId: '12011738615',
    projectId: 'yourvenue-34441',
    authDomain: 'yourvenue-34441.firebaseapp.com',
    storageBucket: 'yourvenue-34441.firebasestorage.app',
    measurementId: 'G-H228QEBNWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAADwVGUlf7rAD_AnOsXhCD4R_i1NilDpE',
    appId: '1:12011738615:android:25ed75f43c02b53a874af2',
    messagingSenderId: '12011738615',
    projectId: 'yourvenue-34441',
    storageBucket: 'yourvenue-34441.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQJF1eWEPxAwudJKNoGAfIqv8g8zurIWg',
    appId: '1:12011738615:ios:4ee5e53b8ccb2619874af2',
    messagingSenderId: '12011738615',
    projectId: 'yourvenue-34441',
    storageBucket: 'yourvenue-34441.firebasestorage.app',
    androidClientId: '12011738615-7rrh9fu3v06vol2v8vpo4qd1dr0pvlre.apps.googleusercontent.com',
    iosClientId: '12011738615-brf2dpqqv3cohm30qcp8a6m73ea8uqh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourVenueManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQJF1eWEPxAwudJKNoGAfIqv8g8zurIWg',
    appId: '1:12011738615:ios:4ee5e53b8ccb2619874af2',
    messagingSenderId: '12011738615',
    projectId: 'yourvenue-34441',
    storageBucket: 'yourvenue-34441.firebasestorage.app',
    androidClientId: '12011738615-7rrh9fu3v06vol2v8vpo4qd1dr0pvlre.apps.googleusercontent.com',
    iosClientId: '12011738615-brf2dpqqv3cohm30qcp8a6m73ea8uqh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourVenueManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAneAIVn0M_zfFQhkVrPw-RoSm-x0FIN8w',
    appId: '1:12011738615:web:a1ba6ad4132fccf8874af2',
    messagingSenderId: '12011738615',
    projectId: 'yourvenue-34441',
    authDomain: 'yourvenue-34441.firebaseapp.com',
    storageBucket: 'yourvenue-34441.firebasestorage.app',
    measurementId: 'G-MGMRW746ER',
  );
}
